### ISSUE TITLE
Missing translation for Korean

### ISSUE THREAD

**Issue by DDinghoya** [AxionDrak/GameCube-Backup-Manager#101]
Information about added languages is missing from the source frmConfig.ko.resx. It is confirmed that frmConfig.resx exists properly.

I think that the following items should be added and translated in frmConfig.ko.resx.

Français [FR] -> 프랑스어 [FR]
Deutsch [DE] -> 독일어 [DE]
日本 [JA] -> 일본어 [JA]

other, Translation of line 284 of frmConfig.es.resx has been completed, but it is not being applied.

"Deshabilitar la pantalla de bienvenida al iniciar el programa (Splash Screen)" -> 프로그램 시작 시 시작 화면 비활성화 (스플래쉬 스크린)

![2nd](https://user-images.githubusercontent.com/19677686/189681353-ea433c0a-d65f-424c-8e2c-90aa4d66a00a.png)

Please review the two points mentioned above.

**Comment by sjohnson1021** [comment]
Not sure if you already pushed these changes in the recent pull requests, on my phone and can't dig right now, but relevant to translation/Localization and in the effort to expedite future improvements/changes I've exported the most recent resource string assets to a Google Sheet that's publicly editable. And thanks to Google, Congress with built in version history, and the usual suite of Google doc features.

https://github.com/AxionDrak/GameCube-Backup-Manager/discussions/92#discussioncomment-3657543

**Comment by DDinghoya** [comment]
> Not sure if you already pushed these changes in the recent pull requests, on my phone and can't dig right now, but relevant to translation/Localization and in the effort to expedite future improvements/changes I've exported the most recent resource string assets to a Google Sheet that's publicly editable. And thanks to Google, Congress with built in version history, and the usual suite of Google doc features.
> 
> [#92 (comment)](https://github.com/AxionDrak/GameCube-Backup-Manager/discussions/92#discussioncomment-3657543)
> 
> > ## [Google Sheet - GCBM Localization Project ](https://docs.google.com/spreadsheets/d/1YyImjM7hPkJPdr_8nmBuiRnnrPzdmb2J/edit?usp=drivesdk&ouid=113862669718221596237&rtpof=true&sd=true)

Yup! I checked google translation sheet and Done! :)

Thank you!
