### ISSUE TITLE
Failed to download cover 3D (or any other graphic), 404 Not Found

### ISSUE THREAD

**Issue by dogchainx** [AxionDrak/GameCube-Backup-Manager#106]
I get this error in the Log when I try to download covers.  I'm not seeing any INI or other file/setting to check on where these are downloaded from, since its 404 Not Found.

EDIT: Searched the code. Looks like GameID for the link to https://art.gametdb.com/wii/disc/ <INSERT GAME INFO> is "0x00", since that is what shows in the field of Game ID in the DETAILS part on the main form on the right side.  It doesn't update, at least on my install, of the ID Game Code, such as https://art.gametdb.com/wii/disc/US/PZLE01.png for Zelda gamecube. 

So I think the program tries to download from https://art.gametdb.com/wii/disc/US/0x00.png, which doesn't exist.

> **[2022-10-27 14:49:48] [ERROR] The remote server returned an error: (404) Not Found.
>    at System.Net.HttpWebRequest.GetResponse()
>    at GCBM.frmMain.DownloadOnlyDisc3DCoverSelectedGame(DataGridView dgv)[2022-10-27 14:49:48] [ERROR] Failed to download cover (3D)!
> [2022-10-27 14:49:48] [ERROR] The remote server returned an error: (404) Not Found.
>    at System.Net.HttpWebRequest.GetResponse()
>    at GCBM.frmMain.DownloadOnlyDisc3DCoverSelectedGame(DataGridView dgv)**

![Gamecube program](https://user-images.githubusercontent.com/7515795/198507439-79a3113d-76d1-4a35-bcee-da96a7ef2204.png)

**Comment by bocarlsson3rd** [comment]
Having the same problem. The game ID is correct but disc ID is not.

2022-11-22 09:38:26] [ERROR] Failed to Download covers (Disc)

 [ERROR] The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.GetResponse()
   at GCBM.frmMain.DownloadOnlyDisc3DCover(DataGridView dgv)[2022-11-22 09:38:26] [ERROR] Failed to download cover (3D)!
 [ERROR] The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.GetResponse()
   at GCBM.frmMain.DownloadOnlyDisc3DCover(DataGridView dgv)[2022-11-22 09:38:26] [ERROR] Failed to Download covers (Disc)

![image](https://user-images.githubusercontent.com/46034610/203273119-d9db1e99-b52f-4cd3-98e6-2747746c34ae.png)

**Comment by dogchainx** [comment]
Its been awhile since I've installed Visual Studio, but going to look more into it in the next few weeks.  I'm sure its something easily resolved, I just need to see how the code flow with grabbing the Game/Disc ID.   


**frmMain.cs** line **1296** is the code for the function **DownloadOnlyDisc3DCoverSelectedGame**.  This is where the error happens and is shown in the log.

I haven't figured out how to run the code yet, and step into each variable.  But something is causing it, possibly the **_IDMakerCode** string.

**Comment by sjohnson1021** [comment]
> I get this error in the Log when I try to download covers. I'm not seeing any INI or other file/setting to check on where these are downloaded from, since its 404 Not Found.
> 
> EDIT: Searched the code. Looks like GameID for the link to https://art.gametdb.com/wii/disc/ is "0x00", since that is what shows in the field of Game ID in the DETAILS part on the main form on the right side. It doesn't update, at least on my install, of the ID Game Code, such as https://art.gametdb.com/wii/disc/US/PZLE01.png for Zelda gamecube.
> 
> So I think the program tries to download from https://art.gametdb.com/wii/disc/US/0x00.png, which doesn't exist.
> 
> > **[2022-10-27 14:49:48] [ERROR] The remote server returned an error: (404) Not Found.
> > at System.Net.HttpWebRequest.GetResponse()
> > at GCBM.frmMain.DownloadOnlyDisc3DCoverSelectedGame(DataGridView dgv)[2022-10-27 14:49:48] [ERROR] Failed to download cover (3D)!
> > [2022-10-27 14:49:48] [ERROR] The remote server returned an error: (404) Not Found.
> > at System.Net.HttpWebRequest.GetResponse()
> > at GCBM.frmMain.DownloadOnlyDisc3DCoverSelectedGame(DataGridView dgv)**
> 
> ![Gamecube program](https://user-images.githubusercontent.com/7515795/198507439-79a3113d-76d1-4a35-bcee-da96a7ef2204.png)

Terribly sorry, yeah you were right there, _IDMakerCode was/is a remnant of how game information used to be stored (one at a time, in global variables). This should've been, and has been corrected to game.ID.

Thank you for your patience and for pointing this out. kudos for debugging and going the extra mile. If I had cleaned up the code properly and gotten rid of old remnants fully instead of unhooking them, and slowly taking them out, you probably would've had a much easier time. As it is.. the code is messy even for me to come back to ..

**Comment by dogchainx** [comment]
You're very welcome!

I haven't programmed for a long time, so was fun to parse through the code and do some sleuthing.  Though I'm sure you'd be able to figure this out in a few moments without any assistance.

Thanks for updating this.  My son will be thrilled.



Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
