### ISSUE TITLE
Issues found (v2.5.x.x)

### ISSUE THREAD

**Issue by laetemn** [AxionDrak/GameCube-Backup-Manager#24]
I found some problems in the following functions:

- Progress bar while transferring 3 or more games enters eternal loop mode, forcing to close and reopen the program;
- In the "Files (Target)" tab, the Combobox intended to select the target device is not being automatically loaded when starting the program;
- In the "Database" tab, the Combobox destined for the filter is not being automatically loaded when starting the program;
- The "Database" tab is not loading the contents of the wiitdb.xml file (even with the option selected in the settings);

Note: These functions work perfectly in version 2.4.6.0 and earlier.

**Comment by laetemn** [comment]
I have reviewed the code and compared it to version 2.4.6.0, and apparently there is nothing wrong, however, the respective functions are no longer working in the latest versions of GCBM. >_<

**Comment by sjohnson1021** [comment]
... Will definitely look at that. Put that other thing on pause. Sorry for the delay.

**Comment by sjohnson1021** [comment]
Yeah.. That's my fault. Pushing to main. Still looking at the transfers. It's working on my local branch. but.. well. y'know.

**Comment by sjohnson1021** [comment]
https://github.com/AxionDrak/GameCube-Backup-Manager/compare/main...main-fix-combobox-and-loadDB
