### ISSUE TITLE
Duplicated icon in the taskbar

### ISSUE THREAD

**Issue by xxmichibxx** [AxionDrak/GameCube-Backup-Manager#3]
The GCBM icon duplicates after switching the language to english.

Example: https://imgur.com/YRzuuV3

Used version: 2.4.3.0
System: Windows 10 Enterprise 21H2 build 19044.1526

**Comment by laetemn** [comment]
> The GCBM icon duplicates after switching the language to english.
> 
> Example: https://imgur.com/YRzuuV3
> 
> Used version: 2.4.3.0 System: Windows 10 Enterprise 21H2 build 19044.1526

This error has been confirmed and should be corrected in a future version of the program.
This error does not affect the functioning of the program, being only aesthetic.
