### ISSUE TITLE
CODE CLEANUP!!!

### ISSUE THREAD

**Issue by laetemn** [AxionDrak/GameCube-Backup-Manager#39]
Code cleanup.
Removal of unused functions (obsolete due to lack of update and fixes).

Functions removed:
- Burn Media CD/DVD (frmBurnMedia)
- Create App Package (frmCreateAppPackage)
- Create Package (frmCreatePackage)
- Test Game Dolphin Emulator (frmDolphinEmulator)
- Install App (frmInstallApp)
- Manage App (frmManageApp)

NOTE: unused functions must return in a future version of the program (WPF) as plugins.

**Comment by sjohnson1021** [comment]
Oooh, so that is a tentative green light for further work on that?

**Comment by laetemn** [comment]
> Oooh, so that is a tentative green light for further work on that? After we get the wiiTDB and update stuff fixed, and stability tweaks/polish etc.

Yup.
The objective is to carry out a wide cleaning of the code, aiming at a leaner, more agile and easy to maintain code.
No new features will be added, as this would eventually bring new bugs.

The new features will be added in a rewritten version of the program (WPF...).
