### ISSUE TITLE
App unable to connect to internet.

### ISSUE THREAD

**Issue by Bentheminernz** [AxionDrak/GameCube-Backup-Manager#4]
Just installed this app but it won't connect to the internet so I can't download the GameTDB data and I can't seem to find a place to manually locate because I just downloaded it myself but there isn't a button to tell it where it's located.

**Comment by laetemn** [comment]
First you need to configure the program.

1 - In the main window of the program, click on 'Options', then 'Settings'.

2 - In the settings screen, go to the 'Several' tab and check the option 'Check internet connection when starting program'.

3 - Still in the settings screen, go to the 'Titles' tab and check the option 'Use commercial name for the game via wiitdb.xml' (RECOMMENDED!)

4 - Close the settings screen.

5 - On the program's main screen, go to the 'Database' tab and click on the 'Tools' option, then 'GameTDB Update'.

NOTE: if desired. change the program language in the 'Languages' tab (you need to restart the program for it to take effect).

SUMMARY: After configuring the program, click on the option indicated in the image.

![database](https://user-images.githubusercontent.com/273767/167298670-19a455ca-4f16-4dea-a7ed-a7e660f648b9.png)
