### ISSUE TITLE
TODO: Utilize toDataTable function.

### ISSUE THREAD

**Issue by sjohnson1021** [AxionDrak/GameCube-Backup-Manager#41]
Should be fairly self explanatory.

Call GameList once on DisplayFilesSelected, once we have the list, -> toDataTable. dgv.DataSource = [the resulting table]

this way we could just databind the tbID,name,region to dgv.CurrentRow.Cells["ID"], dgv.CurrentRow...  .... and call dgv.Databind() on SelectedRow/Index changed.

**Comment by laetemn** [comment]
hum... If I understand correctly, this would reduce unnecessary calls and increase performance, making the program more responsive.

It's a good approach and can be tested on a separate branch, if all goes well, merge into the main branch.

**Comment by sjohnson1021** [comment]
Question is.. will I also have to isolate/optimize the methods involving actually getting title/region/id before or along the way, or will I be able to split the tasks up.. Because.. the first part is.. a bit of a headache. We'll see.
