### ISSUE TITLE
Bug: Files (Destination) tab incompatible with displaying Detailed Information from Display menu

### ISSUE THREAD

**Issue by jmynes** [AxionDrak/GameCube-Backup-Manager#46]
**Expected behavior:**
Detailed Information should display when selecting the option from the `Files (Destination)` tab

**Description of issue:**
From the `Files (Destination)` tab, when selecting `Display > Detailed information (of the selected game)`, a prompt erroneously appears informing me I haven't selected a game from the list:

"Please select a game from the list!"
![image](https://user-images.githubusercontent.com/15176546/180690659-bce0d56f-dc1a-4c3c-8deb-99971dab598d.png)

---

This option _does_ work from the `Files (Source)` tab, but not from the `Files (Destination)` tab:
![image](https://user-images.githubusercontent.com/15176546/180691549-05631f18-885a-4cf1-a4df-853996920c1f.png)

**Comment by sjohnson1021** [comment]
`            int _selectedGameRowCount = dgvSource.Rows.GetRowCount(DataGridViewElementStates.Selected);

Changed to:

`            int _selectedGameRowCount = dgvSelected.Rows.GetRowCount(DataGridViewElementStates.Selected);
