### ISSUE TITLE
Feature Request: Loading / Progress bar when populating Files (Source) or running Reload List

### ISSUE THREAD

**Issue by jmynes** [AxionDrak/GameCube-Backup-Manager#51]
When loading 50+ ISOs, or reloading a large list of ISOs with only a few additions, Gamecube Backup Manager starts to hang, and even displays `(Not Responding)` in the title bar:

![image](https://user-images.githubusercontent.com/15176546/180916325-90fd3881-51f2-4d8a-9fd1-687eb18ed595.png)

The application has not actually hung, it is just busy loading ISOs in the background; this is unclear to the user, and looks like it has crashed.

**Comment by sjohnson1021** [comment]
Working on this now.. also working on optimizing using titles from WiiTDB as that takes... FOREVER atm. Not sure why.

**Comment by sjohnson1021** [comment]
Okay, so documenting here.. one approach would be:

Build a queue System, and intentionally iterate slower and manually through each game when loading a folder, updating a ProgressBar (placed at bottom left, status bar position?) 

Another approach would be (and this would be the .. preferred, but unrealistic goal), make method asynchronous properly, and implement Task Queue system . Going to try working with # 1, since.. well. its easier, and more likely to get done, sooner.

**Comment by sjohnson1021** [comment]
https://youtu.be/3h54LiCffv4
Pssst

**Comment by sjohnson1021** [comment]
Thought of a slight rework to the loop, similar to the structure /behavior taken with the batch installs.

```
OFD
	Get Files
	Store string[]
	Start loop
               \/
     ->(Task: loop) string[].first() => GetGameInfo=>game
    ^<<<<<<<<<-  =>  dgv.Add(game)
                     | =>  await Task -> \?/ (if (string == string[].last) => \/
                    ^-==-----------------<-                                             \/
												Done
```

**Comment by sjohnson1021** [comment]
> When loading 50+ ISOs, or reloading a large list of ISOs with only a few additions, Gamecube Backup Manager starts to hang, and even displays `(Not Responding)` in the title bar:
> 
> ![image](https://user-images.githubusercontent.com/15176546/180916325-90fd3881-51f2-4d8a-9fd1-687eb18ed595.png)
> 
> The application has not actually hung, it is just busy loading ISOs in the background; this is unclear to the user, and looks like it has crashed.


So uh.. Take a loot at 
[gcbm.2.6.0.11.zip](https://github.com/AxionDrak/GameCube-Backup-Manager/files/9508948/gcbm.2.6.0.11.zip)
This is todays build. I think you'll like it
@jmynes
