### ISSUE TITLE
Bug: Certain nkit.iso formatted backups do not work with Gamecube Backup Manager

### ISSUE THREAD

**Issue by jmynes** [AxionDrak/GameCube-Backup-Manager#53]
**Expected behavior:**
Any valid "good" dump of a game ISO, converted to NKit v1.4's `.nkit.iso` format, should be importable in Gamecube Backup Manager.

**Description of issue:**
A rare few of my good dumps, once converted to `.nkit.iso`, do not import in Gamecube Backup Manager, and instead throw the error: `The image is too small!`

---

**Files I've received this error message from, so far:**
- Title: `Casper - Spirit Dimensions (USA).nkit.iso`
  - Game ID: `GS9E6S`
  - md5sum: `76f062b4ae094780d371e47fdf0702ef`
  - CRC-32: `afae94cd`

- Title: `Mario Power Tennis (USA) (Rev 1).nkit.iso`
  - Game ID: `GOME01`
  - md5sum: `60752fd6c7037486b599653b3045cad1`
  - CRC-32: `ef719371`

- Title: `Shrek Extra Large (USA).nkit.iso`
  - Game ID:** `GS9E6S`
  - md5sum: `e54b297ea5d89a2e6d98a81a04ed6df6`
  - CRC-32: `f2b6e2c1`

---

**Dolphin's `Properties > Verify` tab does not report any _unique errors_ with these files**
The below errors display on **__all__** of my 200+ `.nkit.iso` files, but only the above 3 give Gamecube Backup Manager trouble, so far:

> "This disc image has an unusual size. This will likely make the emulated loading times longer. When using NetPlay or sending input recordings to other people, you will likely experience desyncs if anyone is using a good dump."

> "This disc image is in the NKit format. It is not a good dump in its current form, but it might become a good dump if converted back. The CRC32 of this file might match the CRC32 of a good dump even though the files are not identical."

--- 

However, if I convert these files back to full-sized ISOs, Dolphin now shows the message `This is a good dump.`, as expected.

The full-sized version of these ISOs can be read by Gamecube Backup Manager, without issue;
The trimmed versions created by NKit v1.4 do not.

The interesting thing about this is that running the `Install Game (Scrub)` operation against these files results in `game.iso` files which are approximately the same size as the `.nkit.iso` files, anyway.

The resulting `game.iso` files in Dolphin report:

> "This disc image has an unusual size. This will likely make the emulated loading times longer. You will likely be unable to share input recordings and use NetPlay with anyone who is using a good dump."

**Comment by Brycey92** [comment]
I'm also getting the `The image is too small!` error with the following games:

- Title: `Grooverider Slot Car Thunder.nkit.iso`
  - Game ID: `GVRE7H`
  - md5sum: `b92725ea559d70f051f7098d680fec12`
  - CRC-32: `9dd1131e`

- Title: `Tonka - Rescue Patrol`
  - Game ID: `GTQE6S`

**Comment by jmynes** [comment]
Is this issue considered closed since PR #59 was merged in?
Is any further testing or messaging to the user required?

**Comment by Brycey92** [comment]
I would defnitely not consider #59 a fix for this issue, it's just a temporary measure to let the program be used with nkit.iso files for now without throwing size errors. There are no checks to make sure the nkit.iso file is valid, beyond reading the header data. Even worse is that this fix does nothing for the installed files once they get named to `game.iso` or `disc2.iso`. The program will not recognize that they're nkit.iso files, and continues to throw the same image too small error.

Since the changes in #59 are still better than nothing, I made a PR for them despite all these shortcomings, but someone who understands nkit.iso format will need to add file format checks beyond file extension, and also add integrity checks.

**Comment by sjohnson1021** [comment]
## @Brycey92 @jmynes @laetemn Can we discuss further on #42 ?
<img width="452" alt="Screenshot 2022-09-01 155142" src="https://user-images.githubusercontent.com/8071133/188010368-07fbc6ed-9f97-4b12-a303-a31bca1fb439.png">
