### ISSUE TITLE
Langauge settings does not work

### ISSUE THREAD

**Issue by fei0316** [AxionDrak/GameCube-Backup-Manager#54]
The language settings does not change the language for a lot of the UI elements where they stay in Portuguese. I tried changing the language setting back and forth (English to Portuguese then back to English) and nothing changes, still mostly Portuguese with some English text. It seems to be the same when I change it to Korean too. The only difference on my side (since I don't see anyone else complaining) is that my Windows language is Chinese. Let me know if more information is needed. Thank you.

**Comment by Brycey92** [comment]
#47 helps a lot with this issue. If you know your way around git, github, and visual studio, you can check out that branch and compile with it to try it out.

**Comment by jmynes** [comment]
#47 got merged in, just waiting for @sjohnson1021 @laetemn to push a new Release build

**Comment by sjohnson1021** [comment]
> #47 got merged in, just waiting for @sjohnson1021 or @laetemn to push a new Release build

Build published with the new contributions. Thanks a ton

**Comment by jmynes** [comment]
Is this issue considered closed since PR #47 was merged in?

**Comment by fei0316** [comment]
I can confirm whether the new build fixes the problem I'm having tonight then close it.

**Comment by fei0316** [comment]
Hello all, thanks very much for the new version, but it does not seem to work on my computer. I first tried installing the new version over the existing old installation but the language problem persists. Then I tried removing the install and then installing it, and it does not start at all. I tried uninstalling and installing multiple times with no success.

**Comment by sjohnson1021** [comment]
> Hello all, thanks very much for the new version, but it does not seem to work on my computer. I first tried installing the new version over the existing old installation but the language problem persists. Then I tried removing the install and then installing it, and it does not start at all. I tried uninstalling and installing multiple times with no success.

For clarity's sake: 

You 

1. Uninstalled or deleted the program folder
2. Downloaded the latest setup/zip
3. Installed/Extracted

and the program simply refuses to launch?

**Comment by fei0316** [comment]
Sorry for the late reply. I just tested it on my laptop running Windows 10 English. So the summary is that zip version works on both machines but installer version works on neither machines. 

Regarding the language settings problem, it seems like the problem is still there. I basically opened the app, check the text, switch to English/Portuguese, restart the app. After doing this two times I can reproduce the mixed language issue on both machines. The only difference is that on my Chinese machine, choosing Portuguese is alright while choosing English will still have a lot of Portuguese text; on my English machine it's the other way around: English is alright but Portuguese has English text mixed in.

**Comment by sjohnson1021** [comment]
> Sorry for the late reply. I just tested it on my laptop running Windows 10 English. So the summary is that zip version works on both machines but installer version works on neither machines. 
> 
> Regarding the language settings problem, it seems like the problem is still there. I basically opened the app, check the text, switch to English/Portuguese, restart the app. After doing this two times I can reproduce the mixed language issue on both machines. The only difference is that on my Chinese machine, choosing Portuguese is alright while choosing English will still have a lot of Portuguese text; on my English machine it's the other way around: English is alright but Portuguese has English text mixed in.

Okay. That helps, the installer I believe includes my pre built config.ini file, which is why it won't launch . Someone else brought this up, and I fixed the zip file. Apparently I never got around to rebuilding the installer.

Thank you.

Regarding the mixed text.. I'm not seeing much if any mixed text, on English, but I'm aware the translation has been handled.. well, the best it could be at the time. But it needs attention for sure.

**Comment by sjohnson1021** [comment]
> Sorry for the late reply. I just tested it on my laptop running Windows 10 English. So the summary is that zip version works on both machines but installer version works on neither machines.
> 
> Regarding the language settings problem, it seems like the problem is still there. I basically opened the app, check the text, switch to English/Portuguese, restart the app. After doing this two times I can reproduce the mixed language issue on both machines. The only difference is that on my Chinese machine, choosing Portuguese is alright while choosing English will still have a lot of Portuguese text; on my English machine it's the other way around: English is alright but Portuguese has English text mixed in.

When you get a chance, could you test the latest build? Ideally completely remove the previous installation just in case something is amiss with the config (Really no reason there should be). I will look into different methods of getting the language, but.. that really should only matter for the very first launch when it writes the config.ini. Once written, you can select which language you wish to use, and it should apply globally. All four languages currently work for me, on Windows 11 (English). I'm not sure if having the system language be in Chinese would matter or not, seeing as it's reading from a local resource file anyway, and the language is hard saved in the config on first launch, and when you update it from the options form.

Another possibility.. would be adding a Chinese translation, which.. I mean, yeah . eventually. I would only be able to estimate with Google translate, and sometimes.. that can be comical. other times. downright confusing, or potentially dangerous to files ('oops I didn't think that was going to delete that'., etc)

I could export the current resource file in an excel format, for translation, and add it if someone were willing to at least verify  that it makes sense and is coherent before publishing.

**Comment by fei0316** [comment]
I tested both the installer and portable editions of the latest version on my Chinese machine, and everything works as expected: both editions start properly and I cannot reproduce the language switching issue anymore. Thank you!
The only two places where I still see Portuguese when English is selected is on the splash screen of first start (pretty minor I would say) and the Download GameTDB option (seems like a new feature so maybe it's just that the string is not there?)

Regarding Chinese translation, I am more than happy to do it! I can do translation for both Simplified and Traditional Chinese. I do know Git so I can most likely make a fork then a PR for the translation. You can open a new ticket and assign it to me if you want.

**Comment by sjohnson1021** [comment]
Are you comfortable using RESX manager? in VS? or should I export to an excel format?

The WiiTDB Download option... you are referring to the MessageBox that appears on launch if you haven't downloaded it and have an internet connection? .. Will look into adjusting exactly where the form is called to ensure the language is being detected and adjusted properly before rendering, but I believe It is working on my end.. I.. have made some further optimizations and trimmed excess with the branch I'm working on to improve transfers though.

**Comment by sjohnson1021** [comment]
> I tested both the installer and portable editions of the latest version on my Chinese machine, and everything works as expected: both editions start properly and I cannot reproduce the language switching issue anymore. Thank you! The only two places where I still see Portuguese when English is selected is on the splash screen of first start (pretty minor I would say) and the Download GameTDB option (seems like a new feature so maybe it's just that the string is not there?)
> 
> Regarding Chinese translation, I am more than happy to do it! I can do translation for both Simplified and Traditional Chinese. I do know Git so I can most likely make a fork then a PR for the translation. You can open a new ticket and assign it to me if you want.

Are you comfortable using RESX manager? in VS? or should I export to an excel format?

The WiiTDB Download option... you are referring to the MessageBox that appears on launch if you haven't downloaded it and have an internet connection? .. Will look into adjusting exactly where the form is called to ensure the language is being detected and adjusted properly before rendering, but I believe It is working on my end.. I.. have made some further optimizations and trimmed excess with the branch I'm working on to improve transfers though.

Opened Ticket #89 @fei0316

**Comment by fei0316** [comment]
Hi, I haven't used Resx manager but should be fun to play around with it! :)

For the download option I'm referring to this:
![圖片](https://user-images.githubusercontent.com/8295915/188241795-430802c8-137a-483f-91b9-520da4482b74.png)

**Comment by sjohnson1021** [comment]
Thanks will fix that, I just fixed the splash screen. The program now detects and adjusts the language before even the splash screen shows. Which.. delays launch a tiny bit.. like 1 second? It bugs me but should be barely, if at all noticeable.

**Comment by sjohnson1021** [comment]
> Hi, I haven't used Resx manager but should be fun to play around with it! :)
> 
> For the download option I'm referring to this: ![圖片](https://user-images.githubusercontent.com/8295915/188241795-430802c8-137a-483f-91b9-520da4482b74.png)

I am unable to assign you to the ticket #89 until you either contribute to the project.. .... dumb, or comment there apparently.

This is ResX manager in VS2022:
<img width="1834" alt="Screenshot 2022-09-02 182842" src="https://user-images.githubusercontent.com/8071133/188246242-b601cb75-8a5d-463d-833d-19b4a48fffc1.png">
<img width="1877" alt="Screenshot 2022-09-02 182821" src="https://user-images.githubusercontent.com/8071133/188246248-3527285b-b688-4da5-b4e4-70ba6c45691e.png">
