### ISSUE TITLE
[OFF] - Returning to work.

### ISSUE THREAD

**Issue by laetemn** [AxionDrak/GameCube-Backup-Manager#60]
Returning to work.
Sorry for the absence.
I had to get away due to health problems related to SARS-COV-2. (COVID-19).

However, now I am 100% recovered! 👍 

=========================

Taking advantage, I was researching the new versions of .NET and other technologies for application development.
I found the .NET 6 + MAUI alternatives because they are multiplatforms.

**Comment by sjohnson1021** [comment]
Welcome back! no worries. Glad you're doing better. I will definitely need to look into those. Just getting back myself, so great timing. Not to mention, seems we've got some new contributors :wave: @Brycey92 @jmynes . Good things on the horizon my friend.

Right now, between work and family stuff, I'm trying to figure out what (probably some stupid little extra step got added to a loop) is making using WiiTDB titles so incredibly slow. I don't think it used to be like that.. so I might have to dig through old code again to see where I goofed.
