### ISSUE TITLE
v2.6.0.3 gcbm.zip contains predefined config.ini

### ISSUE THREAD

**Issue by grimson73** [AxionDrak/GameCube-Backup-Manager#68]
Hello,

First thanks for your work;

The app did not start for me because the application folder is different than the predefined in config.ini. My guess is that config.ini should not be in this zip file. v2.6.0.2 does not contain the config.ini. Also therefore I guess the config.ini should be created when first starting the app.

Regards,
Arian! :)

**Comment by sjohnson1021** [comment]
Fixed, thank you for noticing. My bad.. 😨

**Comment by grimson73** [comment]
Thanks, glad to help (positive feedback)🫡 👍.
