### ISSUE TITLE
Font not auto-scaling in high DPI devices

### ISSUE THREAD

**Issue by aseemsahoo** [AxionDrak/GameCube-Backup-Manager#70]
While running, the fonts look blurry. It looks perfect while designing.

Automatically adapt the size and disposition of controls to different screen DPIs. What it's needed is to change the layout of the elements using a table layout to relocate and resize them correctly in higher DPI screens. It would need to change the `DpiAwareness` setting in the manifest to `PerMonitorV2` to better detect and adapt the form to it.

**Comment by jmynes** [comment]
Can you leave some additional information about your setup for debugging purposes?

e.g.
- Operating System and Version, and is it fully updated?
- Your screen resolution and DPI
- A screenshot of the differences (if it shows up in pictures)
- Any other details that may help

**Comment by sjohnson1021** [comment]
Any update on this?
