### ISSUE TITLE
Reproducable crash - Downloading WiiTDB first launch

### ISSUE THREAD

**Issue by sjohnson1021** [AxionDrak/GameCube-Backup-Manager#71]
On a fresh install, the first time you launch, if you try to view the Database tab while it is downloading, it throws a cross thread error. Because this functionality lives in a different form. Either we need to migrate this functionality to frmMain, or disable the Database tab until it is finished downloading.

**Comment by laetemn** [comment]
> On a fresh install, the first time you launch, if you try to view the Database tab while it is downloading, it throws a cross thread error. Because this functionality lives in a different form. Either we need to migrate this functionality to frmMain, or disable the Database tab until it is finished downloading.

The best option at the moment is to disable the Database tab until the download is complete.

Another option would be to return the warning indicating the need to download the XML file via WiiTDB, giving the user the option of downloading or not at that moment.

It is also interesting to return the progress indicator for the file download via WiiTDB.

**Comment by sjohnson1021** [comment]
This has been addressed with [https://github.com/AxionDrak/GameCube-Backup-Manager/commit/4065b05ed044af215b8281df1c950fdeb9fe91cd](url).

Expected behavior: 

1. Program checks for WiiTDB file && Network Connection
2. if not connected, move on 
3. If connected, and no file, spawn a new frmWiiTDBDownload , download file, move on
4. If connected and file, move on
