### ISSUE TITLE
Release 2.6.0.5 throws IO Exception and app cannot be launched

### ISSUE THREAD

**Issue by hugo-brito** [AxionDrak/GameCube-Backup-Manager#72]
To reproduce, just install and the run the app.
The app does not start, but when inspecting the Event Viewer, we get the following logs:

Nome da aplicação com falha: GCBM.exe, versão: 2.6.0.5, carimbo de data/hora: 0xfee1cfe3
Nome do módulo com falha: KERNELBASE.dll, versão: 10.0.22000.832, carimbo de data/hora: 0x7efab3dc
Código de exceção: 0xe0434352
Desvio de falha: 0x000000000004474c
ID do processo com falha: 0x5418
Hora de início da aplicação com falha: 0x01d8ba41c81c5a09
Caminho da aplicação com falha: C:\Program Files\gcbm\GCBM.exe
Caminho do módulo com falha: C:\WINDOWS\System32\KERNELBASE.dll
ID do Relatório: 1e97588a-7ae7-499a-83c1-925b39925189
Nome completo do pacote com falha: 
ID da aplicação relativa ao pacote com falha: 

--------------------------------------------------

Application: GCBM.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at GCBM.frmMain.UpdateProgram()
   at GCBM.frmMain..ctor()
   at GCBM.Program.Main()

I was able to use the app by installing the app from the prior release (2.6.0.3)

**Comment by sjohnson1021** [comment]
Had some data loss, and apparently Git changes didn't get pushed with the last update, so, reverted and did some re-writing. Have you installed the latest .NET framework, We did just include .NET 4.8, still working out on how to upgrade the C# language level from.. 7.3 *ugh* to something more modern. I think it's the auto updater that is maybe causing issues? or it might be something deeper in the core components that relies on old code.

Any way, new build being pushed shortly. Please let me know if this fixes your issue. Also do try installing .NET 4.8

**Comment by sjohnson1021** [comment]
Oh .. duh. Auto Updater.NET DLL didn't get included in the installer bundle. Will fix..
