### ISSUE TITLE
MIGRATION - GCBM 3.0 (.NET 6 + .NET MAUI)

### ISSUE THREAD

**Issue by laetemn** [AxionDrak/GameCube-Backup-Manager#73]
I would like everyone's opinion on GCBM migration to .NET 6 + .NET MAUI platform.

I believe it would be better to release GCBM version 3.0 only when the program is completely rewritten in .NET 6 + .NET MAUI.

The two main reasons for suggesting the use of .NET 6 + .NET MAUI, account for:

- Ease of programming in C#, allowing you to reuse the current GCBM code.
- The combination of .NET 6 + .NET MAUI makes it possible to develop a multiplatform application (Android, iOS, macOS and Windows) without major difficulties.

For this, a few observations are necessary:

- The current version of GCBM would normally continue its development until it reaches version number 2.9.x.x, at which point it should be fully migrated to .NET 6 + .NET MAUI.
- No new features will be added to the current version of GCBM, only bug fixes and performance improvements should be performed.
- When migrating, GCBM will receive version number 3.0, indicating a major change in its structure and starting a new phase of the project, henceforth, multiplatform.
- The release of GCBM 3.0 could also include the implementation of a plugin system.  Making it easy to implement new features without having to directly change the main code of the program.

#### NOTE: Apparently, an application developed in .NET 6 + .NET MAUI can also run in a more organized way within the Linux operating system.

**Comment by sjohnson1021** [comment]
Already looking into this, excited to be a part of it and help any way I can.

Right now, we're stuck using C# level 7.3 ... current stable version is 11...... 8.0+ has Async streams which makes working with foreach loops asynchronously a breeze. Something I'm currently banging my head against a wall with.

**Comment by laetemn** [comment]
> Also, not sure if you saw it or not, and sorry if it wasn't wanted, didn't originally intend to do it.. but,:
> 
> https://github.com/AxionDrak/GameCube-Backup-Manager/discussions
> 
> GitHub has a kind of forum space, so we could do polls and discussions there, and leave the Issues for.. well.. Issues

I will transfer the text to the Discussion session.
