### ISSUE TITLE
FR - Support for GCZ format

### ISSUE THREAD

**Issue by hardlevel** [AxionDrak/GameCube-Backup-Manager#82]
I have a lot of images in GCZ format would be nice if we could manage then with this amazing app and this format

thanks in advance

**Comment by sjohnson1021** [comment]
> I have a lot of images in GCZ format would be nice if we could manage then with this amazing app and this format
> 
> thanks in advance

Appreciate the communication, but do attempt to search open issues first, to see if your question has been asked before.  No worries, though.

I am going to go ahead and close this since it is a duplicate essentially of #42 .
