### ISSUE TITLE
Change GCIT Bahavior for Batch

### ISSUE THREAD

**Issue by sjohnson1021** [AxionDrak/GameCube-Backup-Manager#85]
GCIT supports batch scrubbing natively through command line... ... I .. will be totally honest. I had no idea of that until today.

... So.. uhm. Yeah.

Rewrite GCIT batch (actually should make it 10x more simple) to simply check if more than one game is selected, if so grab paths, do work.

Psuedo code for later:
```
IEnumerable<Game> SelectedGames;
SelectedGames = GetSelectedGames(dgv);
if(GetSelectedGames(dgv)=0)
     return
else if(GetSelectedGames(dgv)=1
     StartScrub(path)
else{
     List<string> paths= new List<string>();
     foreach (Game game in SelectedGames)
     {
          paths.Add(game.Path);
     }
     StartBatchScrub(paths)
}
```

**Comment by laetemn** [comment]
> GCIT supports batch scrubbing natively through command line... ... I .. will be totally honest. I had no idea of that until today.
> 
> ... So.. uhm. Yeah.
> 
> Rewrite GCIT batch (actually should make it 10x more simple) to simply check if more than one game is selected, if so grab paths, do work.
> 

Welcome to the team... of people who had no idea about this!
I just discovered this... through your post! KKKKK

**Comment by sjohnson1021** [comment]
Hmm, it does clearly state 'command line for batch'.. Maybe it's Just misleading. Either way It is next on the list.
