### ISSUE TITLE
Bug using "scrub" for multi disc games

### ISSUE THREAD

**Issue by s-taylor** [AxionDrak/GameCube-Backup-Manager#9]
When attempting to "Install Game (Scrub)" on disc2 of a multi disc game the program errors.
You can then manually rename the file to disc2.iso and copy to the correct folder but it's annoying.
I can confirm if you are not using the "scrub" option it works fine.

![image](https://user-images.githubusercontent.com/5457267/172793435-c9536f5a-f029-4e96-ad74-9efc6092dc97.png)

Also it seems to leave a "sys" folder hanging around in the directory when using scrub.

Great work on the application though, thankyou !

**Comment by laetemn** [comment]
> Also it seems to leave a "sys" folder hanging around in the directory when using scrub.
> 

The 'sys' folder is an extra copy of the existing system folder inside the ISO/GCM file.

The Nintendont program reads the contents of this folder in case it is difficult to read the same contents within the ISO/GCM file. This folder is small, does not interfere with game performance, and can be removed if desired.

**Comment by laetemn** [comment]
> When attempting to "Install Game (Scrub)" on disc2 of a multi disc game the program errors.
> You can then manually rename the file to disc2.iso and copy to the correct folder but it's annoying.
> I can confirm if you are not using the "scrub" option it works fine.

I couldn't reproduce that error.
During the tests I performed the program worked correctly.

Are you using the latest version of the program (v2.4.5.0)?
It is also highly recommended to enter the 'Settings' section to configure the program to use the 'wiitdb.xml' file, as indicated in the image below.

![dasss](https://user-images.githubusercontent.com/273767/173242833-1135ea06-6382-4ed0-b730-fe925073fe82.png)

**Comment by laetemn** [comment]
Fixed game transfer system to second disc (disk 2) which caused a crash during transfer for some specific games.
