### ISSUE TITLE
Doesn't seem to handle multi-disc games correctly.

### ISSUE THREAD

**Issue by TomTurbine** [AxionDrak/GameCube-Backup-Manager#99]
When it comes to multi-disc games, the second disc is supposed to be put in the same folder as the first disc but labeled "Disc2.iso"

It just puts it in it's own folder like a different game which will impact Nintendont's ability to handle the disc swap I believe.

**Comment by sjohnson1021** [comment]
> When it comes to multi-disc games, the second disc is supposed to be put in the same folder as the first disc but labeled "Disc2.iso"
> 
> It just puts it in it's own folder like a different game which will impact Nintendont's ability to handle the disc swap I believe.
```
           /*
            * Origin:     c:\games\resident evil 4 disc2 (2) [G4BE082]\game.iso
                        * Destination:    c:\games\resident evil 4 disc2 (2) [G4BE082]\disc2.iso
                        * New Destination: c:\games\resident evil 4 [G4BE08]\
                        */
```

**New Destination: c:\games\resident evil 4 [G4BE08]\disc2.iso**
^^ this is accurate correct?

Checking this in code now.

**Comment by sjohnson1021** [comment]
So basically.. Ugh

Take poorly named iso file 'Baten kaitos Origins seconddisc.iso'

Scanned - > Internal name is Baten Kaitos Origins, ID is GK4E01, and Disc ID is 0x01

We have the choice of using xml name if downloaded, though I believe this one is a bad example, as its the same.

When running through GCIT, (scrubbing) I believe it defaults *gcit's behavior* to the game's internal name. Would you want the file then moved from .. Lets go with Eternal wings. The XML title is Baten Kaitos Eternal Wings and the Lost Ocean, but when scrubbed the title is simply Baten Kaitos. If using the xml title (for display at least, if gcit overrides that anyway?) we should then move the file to 'x:\games\Baten Kaitos and the Lost Ocean [GKBEAF]\game.iso' from 'x:\games\Baten Kaitos [GKBEAF]\game.iso' ... 

Right?

**Comment by TomTurbine** [comment]
Did it with a scrubbed install. But just need the disc2.iso put in the same folder as the game.iso

Easy enough to fix manually but many won't know to do that or how to.

**Comment by sjohnson1021** [comment]
> Did it with a scrubbed install. But just need the disc2.iso put in the same folder as the game.iso
> 
> Easy enough to fix manually but many won't know to do that or how to.

Alright, so you don't also need the sys folder from disc 2? I'm assuming since it's a bootloader it would be donated in the first?

**Comment by TomTurbine** [comment]
Still learning how Nintendont works myself so can't give too much definititely but that sounds about right.

Sorry, I wish I could give you better information myself but learning this as I go setting up an old WiiU to replace my nephews old Wii & Gamecube entirely. So don't know too much about it myself yet.

Just know that for Nintendont to work it requires the 2 discs to be in the same folder and like I mentioned.

**Comment by sjohnson1021** [comment]
New release is out
